# NOTE #1: TCP/UDP의 포트 목록(https://ko.wikipedia.org/wiki/TCP/UDP%EC%9D%98_%ED%8F%AC%ED%8A%B8_%EB%AA%A9%EB%A1%9D)
server:
  # 애플리케이션 포트 설정
  port: 80

spring:
  application:
    name: core-shop

  # Databases
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/core_shop
    username: csadmin
    password: 123$

  # JPA
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # 애플리케이션을 처음 실행할 경우 속성값을 create 또는 none 으로 설정
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: false
